global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "backup_alerts.yml"

scrape_configs:
  - job_name: 'timetracking-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'backup-system'
    static_configs:
      - targets: ['backup_monitor:9090']
    scrape_interval: 60s
    metrics_path: '/backup-metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093